<a href="https://colab.research.google.com/github/KirZa-alt/Arrays/blob/main/Arrays_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data=[2,2,4,5,7,8]

array1=np.array(data)

In [ ]:
print(array1.ndim)
print(array1.shape)
print(array1.dtype)

1
(6,)
int64


In [ ]:
array2=np.arange(0,10,2)
''' start stop skip '''
print(array2)

[0 2 4 6 8]


In [ ]:

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
array1[4]

np.int64(7)

In [ ]:
array1[3:6:2]

array([5, 8])

In [ ]:
array1[array1>5]

array([7, 8])

In [ ]:
array1[array1>5]=4
print(array1)

[2 2 4 5 4 4]


In [ ]:
array_one=np.ones((2,3))
print(array_one)

print(array_one[1, :])
print(array_one[1 ,1])

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]
1.0


In [ ]:
arr=np.array([[1,2,3], [4,5,6]])
print(arr[1,1:2])

print(arr[:,1:7])

[5]
[[2 3]
 [5 6]]


In [ ]:
arr1=np.zeros((2,2))
arr1

array([[0., 0.],
       [0., 0.]])

In [ ]:
arr1[0,1]=1
arr1[1,0]=1
arr1

array([[0., 1.],
       [1., 0.]])

In [ ]:
arr3=np.arange(9)
arr3.reshape(1,3,3)
# 1 for3 dimension array

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [ ]:
# channel ,row ,column
# multiply = total no of values

arr4=np.arange(12)
array4=arr4.reshape(1,3,4)

arr5=np.arange(16)
array5=arr5.reshape(2,2,4)
print(array5)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
array5[0,1]

array([4, 5, 6, 7])

In [ ]:
# array5[0:,1]
print(array5[0, 1, 1:3],array5[1,1,1:3])

[5 6] [13 14]


In [ ]:
array5*2

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14]],

       [[16, 18, 20, 22],
        [24, 26, 28, 30]]])

In [ ]:
array5+4

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [ ]:
array5.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [ ]:
# practice
array6=np.arange(20).reshape(5,2,2)
print(array6)


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [ ]:
array6[:1] ,array6[3:4]

(array([[[0, 1],
         [2, 3]]]),
 array([[[12, 13],
         [14, 15]]]))

# **🔰 Tasks for Practice (No Solutions)**
1- What is the shape and number of dimensions of array6?

2- Print only the first 2D block from the array.

3- Access and print the element at block 2, row 1, column 1.

4- Loop through all blocks and print the sum of each block.

5- Reverse the order of the blocks in the array.

6- Print the maximum value in each 2D block.

7- Convert the 3D array into a 1D array (flatten it).

8- Print only the last row of every block.

9- Replace all even numbers in the array with 0.

10- Count how many numbers in the array are greater than 10.

In [ ]:
# answer1
print("shape of array6 is:",array6.shape,"and no of dimension of array6 is:",array6.ndim)

shape of array6 is: (5, 2, 2) and no of dimension of array6 is: 3


array([[[0, 1],
        [2, 3]]])

In [ ]:
# answer 2
array6[:1]

array([[[0, 1],
        [2, 3]]])

In [ ]:
# answer3
array6[1,0,0]

np.int64(4)

In [ ]:
# answer 4
for i in array6:
    sum=np.sum(i)
    print("sum of\n",i, "are: ",sum)

sum of
 [[0 1]
 [2 3]] are:  6
sum of
 [[4 5]
 [6 7]] are:  22
sum of
 [[ 8  9]
 [10 11]] are:  38
sum of
 [[12 13]
 [14 15]] are:  54
sum of
 [[16 17]
 [18 19]] are:  70


In [ ]:
# answer 5
np.flip(array6)

array([[[19, 18],
        [17, 16]],

       [[15, 14],
        [13, 12]],

       [[11, 10],
        [ 9,  8]],

       [[ 7,  6],
        [ 5,  4]],

       [[ 3,  2],
        [ 1,  0]]])

In [ ]:
# answer6
print("max value of each 2D block is:",np.max(array6[:2]),"\nmax value of each 2D block is:",np.max(array6[2:4]))

max value of each 2D block is: 7 
max value of each 2D block is: 15


In [ ]:
# answer7
array6.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# answer8
for i in array6:
    print(i[-1, :])

[2 3]
[6 7]
[10 11]
[14 15]
[18 19]


In [ ]:
# answer9
for i in range(array6.shape[0]):
    for row in range(array6.shape[1]):
        for col in range(array6.shape[2]):
            if array6[i, row, col] % 2 == 0:
                array6[i, row, col] = 0

print(array6)

[[[ 0  1]
  [ 0  3]]

 [[ 0  5]
  [ 0  7]]

 [[ 0  9]
  [ 0 11]]

 [[ 0 13]
  [ 0 15]]

 [[ 0 17]
  [ 0 19]]]


In [ ]:
# answer 10
count=0
for i in range(array6.shape[0]):
    for row in range(array6.shape[1]):
        for col in range(array6.shape[2]):
            if array6[i, row, col] >10:
                count+=1

print(count)

5
